/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home
 */
public class Level extends javax.swing.JFrame {
static int lvl=6;
    /**
     * Creates new form Level
     */
    public Level() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        l1 = new javax.swing.JRadioButton();
        l2 = new javax.swing.JRadioButton();
        l3 = new javax.swing.JRadioButton();
        l4 = new javax.swing.JRadioButton();
        l5 = new javax.swing.JRadioButton();
        l6 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(l1);
        l1.setText("Level1");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 62, -1, -1));

        buttonGroup1.add(l2);
        l2.setText("Level2");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 85, -1, -1));

        buttonGroup1.add(l3);
        l3.setText("Level3");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 108, -1, -1));

        buttonGroup1.add(l4);
        l4.setText("Level4");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 131, -1, -1));

        buttonGroup1.add(l5);
        l5.setText("Level5");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 154, -1, -1));

        buttonGroup1.add(l6);
        l6.setText("Level6");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 177, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CHOOSE DIFFICULTY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 390, -1));

        jButton1.setText("PLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(l1.isSelected())
    lvl=6;
if(l2.isSelected())
    lvl=5;
if(l3.isSelected())
    lvl=4;
if(l4.isSelected())
    lvl=3;
if(l5.isSelected())
    lvl=2;
if(l6.isSelected())
    lvl=1;
this.dispose();
new White_Devil().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton l1;
    private javax.swing.JRadioButton l2;
    private javax.swing.JRadioButton l3;
    private javax.swing.JRadioButton l4;
    private javax.swing.JRadioButton l5;
    private javax.swing.JRadioButton l6;
    // End of variables declaration//GEN-END:variables
}
